### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-sass-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://rocky-retreat-8465.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-sass-intro/1) criteria:
- [x] You're building off [this mock app](https://github.com/chrisvfritz/sinatra-sass-intro-practice/archive/master.zip) (copy those files into your project directory).
- [x] The CSS in `public/stylesheets/sass/app.scss` is refactored according to [the TODO comments in the file](https://github.com/chrisvfritz/sinatra-sass-intro-practice/blob/master/public/stylesheets/sass/app.scss).
- [x] Your client has mentioned they want the page to "pop" more, with _just a hint_ of pizazz. To accomplish this, uncomment and specify override values for all of the commented-out Bootstrap variables, as well as five more you choose from [the Boostrap variables list](http://getbootstrap.com/customize/#less-variables).

**Comment by chrisvfritz** [comment]
_Almost_ perfect!

``` css
.container > footer {
  ...
}
```

isn't exactly the same as:

``` css
.container {
  footer {
    ...
  }
}
```

See if you can figure out why they behave slightly differently. If you get totally stuck though, let me know. :smiley:

**Comment by KatieMFritz** [comment]
Oh. So .container > footer means the footer has to be the direct child, with no other layers between them, while .container footer means the footer just has to be somewhere within .container.

I'm using a descendant selector but I can't remember why. Am I supposed to be using a child selector?

**Comment by chrisvfritz** [comment]
Yes, that's exactly right! This website would works both ways, but I do want to make sure you know how to write that first code block in SCSS. Can you try updating the project?

**Comment by KatieMFritz** [comment]
@chrisvfritz Is this right?
  & > footer: { }
I uploaded the changes so you can see in context too.

**Comment by KatieMFritz** [comment]
Time to ship?

**Comment by chrisvfritz** [comment]
:shipit:
